base/urls.py
from django.urls import path
from base import views

urlpatterns = [
    path('', views.index),
    path('base/', views.base)
]

main/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.contrib.auth.views import logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('preguntas/', include('preguntas.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('reportes/', include('reportes.urls')),
    path('antiguo/', include('reinicio.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', include('base.urls')),
    path('logout/', logout_then_login)
]

preguntas/urls.py
from django.urls import path
from preguntas import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', login_required(views.preguntas), name="preguntas"),
    path('responder/', login_required(views.responder), name="responder"),
    path('respuesta/', login_required(views.respuesta), name="respuesta"),
    path('respuestas/', login_required(views.respuestas), name="respuestas"),
    path('respuestas_n3/', login_required(views.respuestas_n3), name="respuestas_n3"),
    path('respuestas_n2/', login_required(views.respuestas_n2), name="respuestas_n2"),
    path('grafico/', login_required(views.grafico), name="grafico"),
    path('grafico_desconozco/', login_required(views.grafico_desconozco), name="grafico_desconozco"),
    path('elegir_control/', login_required(views.elegir_control), name="elegir_control"),
    path('elegir_control/editar_control/', login_required(views.editar_control), name="editar_control"),
    path('elegir_pregunta/', login_required(views.elegir_pregunta), name="elegir_pregunta"),
    path('elegir_pregunta/editar_pregunta/', login_required(views.editar_pregunta), name="editar_pregunta"),
    path('responder/retroceder', login_required(views.retroceder), name="retroceder"),
    path('elegir_dominio/', login_required(views.elegir_dominio), name="elegir_dominio"),
    path('elegir_dominio/editar_dominio/', login_required(views.editar_dominio), name="editar_dominio"),
    path('elegir_seccion/', login_required(views.elegir_seccion), name="elegir_seccion"),
    path('elegir_seccion/editar_seccion/', login_required(views.editar_seccion), name="editar_seccion"),
    path('editar_respuesta/', login_required(views.editar_respuesta), name="editar_respuesta")
]

preguntas/models.py
from django.db import models
from usuarios.models import User, Empresa

class Dominio(models.Model):
	id_d = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	checklist = models.CharField(max_length=144)
	estandar = models.CharField(max_length=144)
	nombre = models.CharField(max_length=144)

	def __str__(self):
		return str(self.id_d)

class Seccion(models.Model):
	id_s = models.AutoField(primary_key = True, unique=True,null=False, blank = False)
	checklist = models.CharField(max_length=144)
	dominio = models.ForeignKey(Dominio, null=False, blank=False, on_delete=models.CASCADE)
	estandar = models.CharField(max_length=144)
	nombre = models.CharField(max_length=144)

	def __str__(self):
		return str(self.id_s)

class Control(models.Model):
	id_c = models.AutoField(primary_key = True, unique=True,null=False, blank = False)
	checklist = models.CharField(max_length=144)
	seccion = models.ForeignKey(Seccion, null=False, blank=False, on_delete=models.CASCADE)
	estandar = models.CharField(max_length=144)
	nombre = models.CharField(max_length=144)

	def __str__(self):
		return str(self.id_c)

class Pregunta(models.Model):
	id_p = models.IntegerField(primary_key = True, unique=True,null=False, blank = False)
	control = models.ForeignKey(Control, null=False, blank=False, on_delete=models.CASCADE)
	letra = models.CharField(max_length=2)
	nombre = models.TextField()

	def __str__(self):
		return str(self.id_p)

class Respuesta(models.Model):
	id_res = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	usuario_dueño = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
	pregunta = models.ForeignKey(Pregunta, null=False, blank=False, on_delete=models.CASCADE)
	respuesta = models.IntegerField()

	def __str__(self):
		return str(self.id_res)

class DiasEncuestaEmpresa(models.Model):
	empresa = models.ForeignKey(Empresa, null=False, blank=False, on_delete=models.CASCADE)
	fecha_inicio = models.DateTimeField(auto_now_add=True)
	fecha_fin = models.DateTimeField(auto_now_add=False)

	def __str__(self):
		return str(self.empresa)

preguntas/forms.py
from django import forms
from .models import Respuesta, Control, Pregunta, Dominio, Seccion

RESPUESTA = (
	('1','Si'),
	('0','No'),
	('2','Desconozco')
)

class RespuestaForm(forms.ModelForm):
	class Meta:
		model = Respuesta
		fields = ('respuesta',)

		widgets = {
			'respuesta': forms.RadioSelect(
				choices=RESPUESTA
			)
		}

class ControlForm(forms.ModelForm):
	class Meta:
		model = Control
		fields = ('nombre',)

		widgets = {
			'nombre': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			)
		}

class PreguntaForm(forms.ModelForm):
	class Meta:
		model = Pregunta
		fields = ('nombre',)

		widgets = {
			'nombre': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			)
		}

class DominioForm(forms.ModelForm):
	class Meta:
		model = Dominio
		fields = ('nombre',)

		widgets = {
			'nombre': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			)
		}

class SeccionForm(forms.ModelForm):
	class Meta:
		model = Seccion
		fields = ('nombre',)

		widgets = {
			'nombre': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			)
		}

preguntas/views.py
from django.shortcuts import render, redirect
from .models import User, Dominio, Pregunta, Respuesta, Seccion, Control, DiasEncuestaEmpresa
from reportes.models import Intervalos, IntervalosAceptado
from .forms import RespuestaForm, ControlForm, PreguntaForm, DominioForm, SeccionForm
from django.http import Http404, HttpResponse
from usuarios.views import agregar_usuario, agregar_trabajador, agregar_supervisor
from usuarios.models import Logs
import datetime

# Funcion para obtener el id del usuario
def idusuario(request):	
	return request.user.id

def preguntas(request):
	userid=idusuario(request)
	permisos = User.objects.get(id = userid)
	if permisos.autorizacion.id_a == 3:
		return redirect('agregar_trabajador')
	elif permisos.autorizacion.id_a == 2:
		return redirect('agregar_usuario')
	elif permisos.autorizacion.id_a == 1:
		return redirect('/reportes')
	log = Logs(usuario = permisos)
	log.save()
	return redirect('responder')

def retroceder(request):
	userid=idusuario(request)
	falta = Respuesta.objects.filter(
		usuario_dueño = userid).count()
	if falta >= 1:
		Respuesta.objects.filter(
		usuario_dueño = userid, 
		pregunta = falta
		).delete()

	return redirect('responder')

def responder(request):
	template_name = 'responder.html'
	userid=idusuario(request)
	usuario = User.objects.get(id = userid)
	fecha_limite = DiasEncuestaEmpresa.objects.get(empresa = usuario.sucursal.empresa)
	hoy = datetime.datetime.now()
	if fecha_limite.fecha_fin.date() <= hoy.date():
		return redirect('respuesta')
	falta = Respuesta.objects.filter(
		usuario_dueño = userid).count()
	if falta == Pregunta.objects.all().count():
		return redirect('respuesta')
	form = RespuestaForm()
	if request.method == 'POST':
		form = RespuestaForm(request.POST)
		if form.is_valid():
			resp = form.save(commit=False)
			resp.usuario_dueño = User.objects.get(id = userid)
			resp.pregunta = Pregunta.objects.get(id_p = falta+1)
			resp.save()
			return redirect('responder')
	else:
		form = RespuestaForm()

	dominio_actual = Pregunta.objects.get(
		id_p = falta+1)
	cantidad_actual = Respuesta.objects.filter(
			usuario_dueño = userid, 
			pregunta__control__seccion__dominio = dominio_actual.control.seccion.dominio
			).count()
	data = {
		'form' : form,
		'pregunta' : Pregunta.objects.get(
			id_p = falta+1),
		'cantidad_dominio' : Pregunta.objects.filter(
			control__seccion__dominio = dominio_actual.control.seccion.dominio
			).count(),
		'cantidad_actual' : cantidad_actual+1
	}
	return render(request, template_name, data)

def respuesta(request):
	template_name = 'respuesta.html'
	userid=idusuario(request)
	usuario = User.objects.get(id = userid)
	fecha_limite = DiasEncuestaEmpresa.objects.get(empresa = usuario.sucursal.empresa)
	hoy = datetime.datetime.now()
	tiempo = 0
	if fecha_limite.fecha_fin.date() <= hoy.date():
		tiempo = 1
	data = {
		'respuestas' : Respuesta.objects.filter(
			usuario_dueño =  userid
		),
		'tiempo' : tiempo
	}
	return render(request, template_name, data)

def respuestas(request):
	userid=idusuario(request)
	template_name = 'respuestas.html'
	usuario = User.objects.get(id = userid)
	if usuario.autorizacion.id_a == 3:
		respuesta = Respuesta.objects.filter(
				usuario_dueño__sucursal =  usuario.sucursal
			).order_by('pregunta')
		cant_respuesta = Respuesta.objects.filter(
				usuario_dueño__sucursal =  usuario.sucursal
			).count()
	else:
		respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal__empresa =  usuario.empresa
		).order_by('pregunta')
		cant_respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal__empresa =  usuario.empresa
		).count()

	dominio = Dominio.objects.first()

	if cant_respuesta == 0:
		return  HttpResponse('<h1>Aún no existen respuestas en la encuesta</h1>')
	if usuario.autorizacion.id_a == 3:
		intervalo = Intervalos.objects.filter( empresa = usuario.sucursal.empresa).count()
	else:
		intervalo = Intervalos.objects.filter( empresa = usuario.empresa).count()
	if intervalo == 0:
		return  HttpResponse('<h1>Aún no se especifican intervalos en la empresa</h1>')

	si = 0
	no = 0
	cantidad = []
	cant = 0
	cantn = 0
	for x in respuesta:
		if dominio != x.pregunta.control.seccion.dominio:
			cant = si + no
			cant = (si*100)/cant
			cantn = 100-cant
			cantidad.append([dominio, cant, cantn])
			dominio = x.pregunta.control.seccion.dominio
			si = 0
			no = 0 
		if x.respuesta == 0:
			no=no+1
		if x.respuesta == 1:
			si=si+1
	cant = si + no
	cant = (si*100)/cant
	cantn = 100-cant
	cantidad.append([dominio, cant, cantn])
	if usuario.autorizacion.id_a == 3:
		data = {
			'respuesta' : cantidad,
			'dominio' : Dominio.objects.all(),
			'intervalo' :Intervalos.objects.get( empresa = usuario.sucursal.empresa)
			}
	else:
		data = {
			'respuesta' : cantidad,
			'dominio' : Dominio.objects.all(),
			'intervalo' :Intervalos.objects.get( empresa = usuario.empresa)
			}
	return render(request, template_name, data)

def respuestas_n3(request):
	template_name = 'respuestas_n3.html'
	userid=idusuario(request)
	usuario = User.objects.get(id = userid)
	if usuario.autorizacion.id_a == 3:
		respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal =  usuario.sucursal
		).order_by('pregunta')
		cant_respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal =  usuario.sucursal
		).count()
	else:
		respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal__empresa =  usuario.empresa
		).order_by('pregunta')
		cant_respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal__empresa =  usuario.empresa
		).count()

	if cant_respuesta == 0:
		return  HttpResponse('<h1>Aún no existen respuestas en la encuesta</h1>')
	if usuario.autorizacion.id_a == 3:
		intervalo = Intervalos.objects.filter( empresa = usuario.sucursal.empresa).count()
	else:
		intervalo = Intervalos.objects.filter( empresa = usuario.empresa).count()
	if intervalo == 0:
		return  HttpResponse('<h1>Aún no se especifican intervalos en la empresa</h1>')
		
	dominio = Dominio.objects.first()
	seccion = Seccion.objects.first()

	# Dominio
	sid = 0
	nod = 0
	cantidadd = []
	cantd = 0
	cantnd = 0
	for x in respuesta:
		if dominio != x.pregunta.control.seccion.dominio:
			cantd = sid + nod
			cantd = (sid*100)/cantd
			cantnd = 100-cantd
			cantidadd.append([dominio, cantd, cantnd])
			dominio = x.pregunta.control.seccion.dominio
			sid = 0
			nod = 0 
		if x.respuesta == 0:
			nod=nod+1
		if x.respuesta == 1:
			sid=sid+1
	cantd = sid + nod
	cantd = (sid*100)/cantd
	cantnd = 100-cantd
	cantidadd.append([dominio, cantd, cantnd])

	# Seccion
	si = 0
	no = 0
	cantidad = []
	cant = 0
	cantn = 0
	for x in respuesta:
		if seccion != x.pregunta.control.seccion:
			cant = si + no
			cant = (si*100)/cant
			cantn = 100-cant
			cantidad.append([seccion, cant, cantn])
			seccion = x.pregunta.control.seccion
			si = 0
			no = 0 
		if x.respuesta == 0:
			no=no+1
		if x.respuesta == 1:
			si=si+1

	cant = si + no
	cant = (si*100)/cant
	cantn = 100-cant
	cantidad.append([seccion, cant, cantn])
	if usuario.autorizacion.id_a == 3:
		data = {
			'respuesta' : cantidad,
			'respuestad' : cantidadd,
			'dominio' : Dominio.objects.all(),
			'seccion' : Seccion.objects.all(),
			'intervalo' :Intervalos.objects.get( empresa = usuario.sucursal.empresa)
			}
	else:
		data = {
			'respuesta' : cantidad,
			'respuestad' : cantidadd,
			'dominio' : Dominio.objects.all(),
			'seccion' : Seccion.objects.all(),
			'intervalo' :Intervalos.objects.get( empresa = usuario.empresa)
			}

	return render(request, template_name, data)

def respuestas_n2(request):
	template_name = 'respuestas_n2.html'
	userid=idusuario(request)
	usuario = User.objects.get(id = userid)
	if usuario.autorizacion.id_a == 3:
		respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal =  usuario.sucursal
		).order_by('pregunta')
		cant_respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal =  usuario.sucursal
		).count()
	else:
		respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal__empresa =  usuario.empresa
		).order_by('pregunta')
		cant_respuesta = Respuesta.objects.filter(
			usuario_dueño__sucursal__empresa =  usuario.empresa
		).count()

	if cant_respuesta == 0:
		return  HttpResponse('<h1>Aún no existen respuestas en la encuesta</h1>')
	if usuario.autorizacion.id_a == 3:
		intervalo = Intervalos.objects.filter( empresa = usuario.sucursal.empresa).count()
	else:
		intervalo = Intervalos.objects.filter( empresa = usuario.empresa).count()
	if intervalo == 0:
		return  HttpResponse('<h1>Aún no se especifican intervalos en la empresa</h1>')
		
	dominio = Dominio.objects.first()
	seccion = Seccion.objects.first()
	control = Control.objects.first()

	# Dominio
	sid = 0
	nod = 0
	cantidadd = []
	cantd = 0
	cantnd = 0
	for x in respuesta:
		if dominio != x.pregunta.control.seccion.dominio:
			cantd = sid + nod
			cantd = (sid*100)/cantd
			cantnd = 100-cantd
			cantidadd.append([dominio, cantd, cantnd])
			dominio = x.pregunta.control.seccion.dominio
			sid = 0
			nod = 0 
		if x.respuesta == 0:
			nod=nod+1
		if x.respuesta == 1:
			sid=sid+1
	cantd = sid + nod
	cantd = (sid*100)/cantd
	cantnd = 100-cantd
	cantidadd.append([dominio, cantd, cantnd])

	# Seccion
	si = 0
	no = 0
	cantidad = []
	cant = 0
	cantn = 0
	for x in respuesta:
		if seccion != x.pregunta.control.seccion:
			cant = si + no
			cant = (si*100)/cant
			cantn = 100-cant
			cantidad.append([seccion, cant, cantn])
			seccion = x.pregunta.control.seccion
			si = 0
			no = 0 
		if x.respuesta == 0:
			no=no+1
		if x.respuesta == 1:
			si=si+1

	cant = si + no
	cant = (si*100)/cant
	cantn = 100-cant
	cantidad.append([seccion, cant, cantn])

	# control
	sic = 0
	noc = 0
	cantidadc = []
	cantc = 0
	cantnc = 0
	for x in respuesta:
		if control != x.pregunta.control:
			cantc = sic + noc
			if cantc > 0:
				cantc = (sic*100)/cantc
				cantnc = 100-cantc
			else:
				cantc = 0
				cantnc = 0
			cantidadc.append([control, cantc, cantnc])
			control = x.pregunta.control
			sic = 0
			noc = 0 

preguntas/templates/elegir_control.html
{% extends './base.html' %}
{% load static %}
<head>
    {% block head %}
    {% endblock %}

</head>
<body >
	{% block content %}
		<h1 class="page-header">Elegir Control</h1>
			
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<h4 class="panel-title">Controles</h4>
			</div>
			<div class="panel-body">
				<div class="row">
				    {% for control in control %}
				    <br>
				    <div class=" col-6">
				    	<h5> {{ control.nombre }}</h5>
				    </div>
				    <div class="col-1">
						<form action="editar_control/" method="get">
					    {% csrf_token%}
							<input id="id_control" name="id_control" hidden value="{{ control.id_c }}">
							<button type="submit" class="btn btn-primary">Editar</button>

						</form>
					</div>
					<div class="col-1">
						<form action="/preguntas/elegir_pregunta/" method="get">
					    {% csrf_token%}
					    	<input id="id_control" name="id_control" hidden value="{{ control.id_c }}">
							<button type="submit" class="btn btn-info">Preguntas</button>
						</form>
					</div>
					<br><br>
				        
				    {% endfor %}
				</div>
			</div>
		</div>
	{% endblock %}
</body>

</html>

preguntas/templates/elegir_dominio.html
{% extends './base.html' %}
{% load static %}
<head>
    {% block head %}
    {% endblock %}

</head>
<body >
	{% block content %}
		<h1 class="page-header">Elegir Dominio</h1>
			
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<h4 class="panel-title">Dominios</h4>
			</div>
			<div class="panel-body">
				<div class="row">
				    {% for dominio in dominio %}
				    <br>
				    <div class=" col-6">
				    	<h5> {{ dominio.nombre }}</h5>
				    </div>
				    <div class="col-1">
						<form action="editar_dominio/" method="get">
					    {% csrf_token%}
							<input id="id_dominio" name="id_dominio" hidden value="{{ dominio.id_d }}">
							<button type="submit" class="btn btn-primary">Editar</button>

						</form>
					</div>
				    <div class="col-2">
						<form action="/reportes/ver_leyes_dominio/" method="get">
					    {% csrf_token%}
							<input id="id_dominio" name="id_dominio" hidden value="{{ dominio.id_d }}">
							<button type="submit" class="btn btn-success">Ver Leyes/Decretos</button>

						</form>
					</div>
					<div class="col-1">
						<form action="/preguntas/elegir_seccion/" method="get">
					    {% csrf_token%}
					    	<input id="id_dominio" name="id_dominio" hidden value="{{ dominio.id_d }}">
							<button type="submit" class="btn btn-info">Sección</button>
						</form>
					</div>
					<br><br>
				        
				    {% endfor %}
				</div>
			</div>
		</div>
	{% endblock %}
</body>

</html>

preguntas/templates/elegir_pregunta.html
{% extends './base.html' %}
{% load static %}
<head>
    {% block head %}
    {% endblock %}

</head>
<body >
	{% block content %}
		<h1 class="page-header">Elegir Pregunta</h1>
			
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<h4 class="panel-title">Preguntas</h4>
			</div>
			<div class="panel-body">
				<div class="row">
				    {% for pregunta in pregunta %}
				    <br>
				    <div class=" col-8">
				    	<h5> {{ pregunta.nombre }}</h5>
				    </div>
				    <!-- <div class="col-4"> -->
						<form action="editar_pregunta/" method="get">
					    {% csrf_token%}
							<input id="id_pregunta" name="id_pregunta" hidden value="{{ pregunta.id_p }}">
							<button type="submit" class="btn btn-primary">Editar Pregunta</button>
						</form>&nbsp;&nbsp;&nbsp;&nbsp;
						<form action="/reportes/editar_recomendacion/" method="get">
					    {% csrf_token%}
							<input id="id_pregunta" name="id_pregunta" hidden value="{{ pregunta.id_p }}">
							<button type="submit" class="btn btn-primary">Editar Recomendación</button>
						</form>
					<!-- </div> -->
					<br><br>
				        
				    {% endfor %}
				</div>
			</div>
		</div>
	{% endblock %}
</body>

</html>

preguntas/templates/elegir_seccion.html
{% extends './base.html' %}
{% load static %}
<head>
    {% block head %}
    {% endblock %}

</head>
<body >
	{% block content %}
		<h1 class="page-header">Elegir Sección</h1>
			
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<h4 class="panel-title">Secciones</h4>
			</div>
			<div class="panel-body">
				<div class="row">
				    {% for seccion in seccion %}
				    <br>
				    <div class=" col-6">
				    	<h5> {{ seccion.nombre }}</h5>
				    </div>
				    <div class="col-1">
						<form action="editar_seccion/" method="get">
					    {% csrf_token%}
							<input id="id_seccion" name="id_seccion" hidden value="{{ seccion.id_s }}">
							<button type="submit" class="btn btn-primary">Editar</button>

						</form>
					</div>
					<div class="col-1">
						<form action="/preguntas/elegir_control/" method="get">
					    {% csrf_token%}
					    	<input id="id_seccion" name="id_seccion" hidden value="{{ seccion.id_s }}">
							<button type="submit" class="btn btn-info">Control</button>
						</form>
					</div>
					<br><br>
				        
				    {% endfor %}
				</div>
			</div>
		</div>
	{% endblock %}
</body>

</html>

preguntas/templates/respuesta.html
{% extends './base.html' %}
{% load static %}
<head>
    {% block head %}
    	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="{% static './assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static './assets/plugins/DataTables/extensions/Buttons/css/buttons.bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static './assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css' %}" rel="stylesheet" />
	<!-- ================== END PAGE LEVEL STYLE ================== -->
    {% endblock %}

</head>
<body >
	{% block content %}
		<!-- begin page-header -->
		<h1 class="page-header">Respuestas<small> </small></h1>
		<!-- end page-header -->
			
		<!-- begin panel -->
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<h4 class="panel-title">Niveles</h4>
			</div>
			<div class="panel-body">
			
			<!-- begin row -->
			<div class="row">
			    <!-- begin col-10 -->
			    <div class="col-lg-12">
			        <!-- begin panel -->
                    <div class="panel panel-inverse">
                        <!-- begin panel-body -->
                        <div class="panel-body">
                            <table id="data-table-buttons" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                    	<th class="text-nowrap">Dominio</th>
                                    	<th class="text-nowrap">Sección</th>
                                        <th class="text-nowrap">Control</th>
                                        <th class="text-nowrap">Pregunta</th>
                                        <th class="text-nowrap">Respuesta</th>
                                        <th class="text-nowrap">Editar Respuesta</th>
                                    </tr>
                                </thead>
                                <tbody>
                                	{% for respuestas in respuestas %}
                                    <tr class="odd gradeX">
                                    	<td>{{ respuestas.pregunta.control.seccion.dominio.nombre }}</td>
                                    	<td>{{ respuestas.pregunta.control.seccion.nombre }}</td>
                                        <td>{{ respuestas.pregunta.control.nombre }}</td>
                                        <td>{{ respuestas.pregunta.nombre }}</td>
                                        <td>{% if  respuestas.respuesta == 0 %}
												<h6> NO</h6>
											{% endif %}
											{% if  respuestas.respuesta == 1 %}
												<h6> SI</h6>
											{% endif %}
											{% if  respuestas.respuesta == 2 %}
												<h6> Desconozco</h6>
											{% endif %}</td>
                                        <td>
                                        	{% if  tiempo == 0 %}
	                                        	<form method="get" action="/preguntas/editar_respuesta/">
								                {% csrf_token%}
								                	<input id="id_respuesta" name="id_respuesta" hidden value="{{ respuestas.id_res }}">
								    				<button type="submit" class="btn btn-primary">Editar</button>
												</form>
											{% else %}
												Fin Tiempo para Realizar Encuesta
											{% endif %}
										</td>
                                    {% endfor %}
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- end panel-body -->
                    </div>
                    <!-- end panel -->
                </div>
                <!-- end col-10 -->
            </div>
            <!-- end row -->
			</div>
		</div>
	{% endblock %}

	{% block scripts %}

	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static './assets/plugins/DataTables/media/js/jquery.dataTables.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/dataTables.buttons.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.bootstrap.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.flash.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/jszip.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/pdfmake.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/vfs_fonts.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.html5.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.print.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static './assets/js/demo/table-manage-buttons.demo.min.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->

	<script>
		$(document).ready(function() {
			App.init();
			TableManageButtons.init();
		});
	</script>
	{% endblock %}
</body>

</html>