base/urls.py
from django.urls import path
from base import views

urlpatterns = [
    path('', views.index),
    path('base/', views.base)
]

main/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.contrib.auth.views import logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('preguntas/', include('preguntas.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('reportes/', include('reportes.urls')),
    path('antiguo/', include('reinicio.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', include('base.urls')),
    path('logout/', logout_then_login)
]

reportes/urls.py
from django.urls import path
from reportes import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', login_required(views.reporte), name="reporte"),
    path('intervalos/', login_required(views.intervalos), name="intervalos"),
    path('informe/', login_required(views.informe), name="informe"),
    path('gap/', login_required(views.diagnostico), name="diagnostico"),
    path('diagnosticos/', login_required(views.diagnosticos), name="diagnosticos"),
    path('intervalo_aceptado/', login_required(views.intervalo_aceptado), name="intervalo_aceptado"),
    path('editar_recomendacion/', login_required(views.editar_recomendacion), name="editar_recomendacion"),
    path('enviar_recomendaciones_automaticas/', login_required(views.enviar_recomendaciones_automaticas), name="enviar_recomendaciones_automaticas"),
    path('reportes_auto/', login_required(views.reportes_auto), name="reportes_auto"),
    path('reportes_auto/establecer_encargado/', login_required(views.establecer_encargado), name="establecer_encargado"),
    path('cumplido/', login_required(views.cumplido), name="cumplido"),
    path('cumplido/cumplir/', login_required(views.cumplir), name="cumplir"),
    path('aspectoslegales/', login_required(views.aspectoslegales), name="aspectoslegales"),
    path('aspectoslegales/ver_aspectos_legales/', login_required(views.ver_aspectos_legales), name="ver_aspectos_legales"),
    path('aspectoslegales/agregar_aspectos_legales/', login_required(views.agregar_aspectos_legales), name="agregar_aspectos_legales"),
    path('aspectoslegales/ver_aspectos_legales/editar_aspectos_legales/', login_required(views.editar_aspectos_legales), name="editar_aspectos_legales"),
    path('aspectoslegales/ver_aspectos_legales/version_anterior/', login_required(views.version_anterior), name="version_anterior"),
    path('aspectoslegales/ver_aspectos_legales/eliminar_aspectos_legales/', login_required(views.eliminar_aspectos_legales), name="eliminar_aspectos_legales"),
    path('aspectoslegales/restaurar_aspectos_legales/', login_required(views.restaurar_aspectos_legales), name="restaurar_aspectos_legales"),
    path('aspectoslegales/restaurar_aspectos_legales/restaurar_seleccionado/', login_required(views.restaurar_seleccionado), name="restaurar_seleccionado"),
    path('ver_leyes_dominio/', login_required(views.ver_leyes_dominio), name="ver_leyes_dominio"),
    path('ver_leyes_dominio/agregar_leyes_dominio/', login_required(views.agregar_leyes_dominio), name="agregar_leyes_dominio"),
    path('ver_leyes_dominio/eliminar_leyes_dominio/', login_required(views.eliminar_leyes_dominio), name="eliminar_leyes_dominio"),
    path('grafico_recomendaciones/', login_required(views.grafico_recomendaciones), name="grafico_recomendaciones"),
    path('grafico_gantt/', login_required(views.grafico_gantt), name="grafico_gantt")
]

reportes/models.py
from django.db import models
from usuarios.models import Empresa, User, Cargo
from preguntas.models import Pregunta, Dominio

class Intervalos(models.Model):
	id_in = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	empresa = models.ForeignKey(Empresa, null=False, blank=False, on_delete=models.CASCADE)
	inter_alto = models.FloatField(default = 100)
	inter_medio = models.FloatField()
	inter_bajo = models.FloatField()
	inter_nulo = models.FloatField()

	def __str__(self):
		return str(self.id_in)

class Diagnostico(models.Model):
	id_di = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	empresa = models.ForeignKey(Empresa, null=False, blank=False, on_delete=models.CASCADE)
	usuario_dueño = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	modified_at = models.DateTimeField(auto_now=True)
	vigencia = models.DateTimeField('Vigencia de la medida',auto_now_add=False)
	recomendacion = models.TextField()
	observaciones = models.TextField(blank=True)
	active = models.BooleanField(default=True)
	cumplimiento = models.BooleanField(default=False)

	def __str__(self):
		return str(self.empresa)

class RecomendacionAuto(models.Model):
	id_rec = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	pregunta = models.ForeignKey(Pregunta, null=False, blank=False, on_delete=models.CASCADE)
	cargo_recomendado = models.ForeignKey(Cargo, null=False, blank=False, on_delete=models.CASCADE)
	vigencia = models.IntegerField('cantidad de días')
	recomendacion = models.TextField()
	observaciones = models.TextField(blank=True)
	active = models.BooleanField(default=True)

	def __str__(self):
		return str(self.id_rec)

class Cumplimiento(models.Model):
	id_cump = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	usuario_delegado = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
	fecha_cumplido = models.DateTimeField(auto_now=True)
	recomendacion = models.ForeignKey(RecomendacionAuto, null=False, blank=False, on_delete=models.CASCADE)
	cumplimiento = models.BooleanField(default=False)

	def __str__(self):
		return str(self.id_cump)

class IntervalosAceptado(models.Model):
	id_inac = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	empresa = models.ForeignKey(Empresa, null=False, blank=False, on_delete=models.CASCADE)
	inter_aceptado = models.IntegerField()

	def __str__(self):
		return str(self.id_inac)

class RecoAutoEmpresa(models.Model):
	id_recaem = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	empresa = models.ForeignKey(Empresa, null=False, blank=False, on_delete=models.CASCADE)
	recomendacion = models.ForeignKey(RecomendacionAuto, null=False, blank=False, on_delete=models.CASCADE)
	cumplimiento = models.ForeignKey(Cumplimiento, null=True, blank=True, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True, null = True)
	inicio_vigencia = models.DateTimeField(auto_now_add=False, null = True)
	vigencia = models.DateTimeField(auto_now_add=False, null = True)

	def __str__(self):
		return str(self.id_recaem)

class AspectosLegales(models.Model):
	id_asl = models.AutoField(primary_key = True, unique=True, null=False, blank = False)
	descripcion = models.CharField(max_length=144)
	tipo_norma = models.CharField(max_length=144)
	fecha_publicacion = models.DateTimeField(auto_now_add=False)
	fecha_promulgacion = models.DateTimeField(auto_now_add=False)
	organismo = models.CharField(max_length=144)
	titulo = models.TextField()
	tipo_version = models.CharField(max_length=144)
	inicio_vigencia = models.DateTimeField(auto_now_add=False)
	id_norma = models.IntegerField()
	texto_derogado = models.CharField(max_length=144, blank = True, null=True)
	ultima_modificacion = models.DateTimeField(blank = True, auto_now_add=False, null=True)
	url = models.TextField()
	active = models.BooleanField(default=True)
	version = models.IntegerField(default=1)
	version_anterior = models.ForeignKey('AspectosLegales', null=True, blank=True, on_delete=models.CASCADE)
	eliminado = models.BooleanField(default=False)

	def __str__(self):
		return str(self.tipo_norma)

class DominioLeyes(models.Model):
	dominio = models.ForeignKey(Dominio, null=False, blank=False, on_delete=models.CASCADE)
	aspecto_legal = models.ForeignKey(AspectosLegales, null=False, blank=False, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.dominio)


class RecomendacionesLogs(models.Model):
	cumplimiento = models.ForeignKey(Cumplimiento, null=True, blank=True, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	estado = models.BooleanField(default=True)

	def __str__(self):
		return str(self.cumplimiento)

reportes/forms.py
from django import forms
from .models import Intervalos, Diagnostico, IntervalosAceptado, RecomendacionAuto, Cumplimiento, User, AspectosLegales, DominioLeyes

RESPUESTA = (
	('10','10%'),
	('20','20%'),
	('30','30%'),
	('40','40%'),
	('50','50%'),
	('60','60%'),
	('70','70%'),
	('80','80%'),
	('90','90%'),
)

class IntervalosForm(forms.ModelForm):
	class Meta:
		model = Intervalos
		fields = ('inter_medio','inter_bajo','inter_nulo')

		widgets = {
			'inter_medio': forms.Select(
				choices=RESPUESTA
			),
			'inter_bajo': forms.Select(
				choices=RESPUESTA
			),
			'inter_nulo': forms.Select(
				choices=RESPUESTA
			),
		}

class DiagnosticoForm(forms.ModelForm):
	class Meta:
		model = Diagnostico
		fields = ('vigencia','observaciones','recomendacion')

		widgets = {
			'vigencia': forms.DateInput(
				attrs = {
					'class':'form-control',
					'placeholder':'AAAA-MM-DD'
				}
			),
			'observaciones': forms.Textarea(
				attrs = {
					'class':'form-control'
				}
			),
			'recomendacion': forms.Textarea(
				attrs = {
					'class':'form-control'
				}
			)
		}

class IntervalosAcepForm(forms.ModelForm):
	class Meta:
		model = IntervalosAceptado
		fields = ('inter_aceptado',)

		widgets = {
			'inter_aceptado': forms.Select(
				choices=RESPUESTA
			)
		}

class RecomendacionAutoForm(forms.ModelForm):
	class Meta:
		model = RecomendacionAuto
		fields = ('cargo_recomendado', 'vigencia', 'recomendacion', 'observaciones')

		widgets = {
			'vigencia': forms.NumberInput(
				attrs = {
					'class':'form-control'
				}
			),'recomendacion': forms.Textarea(
				attrs = {
					'class':'form-control'
				}
			),'observaciones': forms.Textarea(
				attrs = {
					'class':'form-control'
				}
			)
		}

class CumplimientoForm(forms.ModelForm):
	class Meta:
		model = Cumplimiento
		fields = ('usuario_delegado',)
	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		super().__init__(*args, **kwargs)
		self.fields['usuario_delegado'].queryset =  User.objects.filter(sucursal__empresa = user.empresa, autorizacion = 4)

class CumplimientoSucursalForm(forms.ModelForm):
	class Meta:
		model = Cumplimiento
		fields = ('usuario_delegado',)
	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		super().__init__(*args, **kwargs)
		self.fields['usuario_delegado'].queryset =  User.objects.filter(sucursal__empresa = user.sucursal.empresa, autorizacion = 4)

class AspectosLegalesForm(forms.ModelForm):
	class Meta:
		model = AspectosLegales
		fields = ('descripcion','tipo_norma','fecha_publicacion', 'fecha_promulgacion','organismo','titulo',
			'tipo_version','inicio_vigencia','id_norma','texto_derogado','ultima_modificacion','url', 'active')

		widgets = {
			'descripcion': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			),'tipo_norma': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			),'fecha_publicacion': forms.DateInput(
				format='%Y-%m-%d',
				attrs = {
					'class':'form-control',
					'placeholder':'AAAA-MM-DD'
				}
			),'fecha_promulgacion': forms.DateInput(
				format='%Y-%m-%d',
				attrs = {
					'class':'form-control',
					'placeholder':'AAAA-MM-DD'
				}
			),'organismo': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			),'titulo': forms.Textarea(
				attrs = {
					'class':'form-control'
				}
			),'tipo_version': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			),'inicio_vigencia': forms.DateInput(
				format='%Y-%m-%d',
				attrs = {
					'class':'form-control',
					'placeholder':'AAAA-MM-DD'
				}
			),'id_norma': forms.NumberInput(
				attrs = {
					'class':'form-control'
				}
			),'texto_derogado': forms.TextInput(
				attrs = {
					'class':'form-control'
				}
			),'ultima_modificacion': forms.DateInput(
				format='%Y-%m-%d',
				attrs = {
					'class':'form-control',
					'placeholder':'AAAA-MM-DD'
				}
			),'url': forms.Textarea(
				attrs = {
					'class':'form-control'
				}
			),'active': forms.CheckboxInput(
				attrs = {
				}
			)
		}

class DominioLeyesForm(forms.ModelForm):
	class Meta:
		model = DominioLeyes
		fields = ('aspecto_legal',)
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['aspecto_legal'].queryset =  AspectosLegales.objects.filter(active = True)

reportes/templates/agregar_leyes_dominio.html
{% extends './base.html' %}
{% load static %}
<head>
	{% block head %}
	{% endblock %}

</head>
<body >
	{% block content %}

		<h1 class="page-header">Aspecto Legal</h1>

		<div class="panel panel-inverse" data-sortable-id="ui-widget-2">
			<div class="panel-heading">
                <h4 class="panel-title">Ley o Decreto</h4>
            </div>
            <div class="panel-body">
            	{% if form.errors %}
                    <div class="alert alert-danger">
                        {{ form.errors }}
                    </div>
                 {% endif %}
                <form class="form-horizontal" enctype="multipart/form-data" name="demo-form" method="post">
                {% csrf_token%}
					<div class="form-group row m-b-15">
						<label class="col-md-4 col-sm-4 col-form-label" for="asunto">Elegir Ley o Decreto:</label>
						<div class="col-md-8 col-sm-8">
							{{ form.aspecto_legal }}
						</div>
					</div>
					<div class="form-group row m-b-0">
						<label class="col-md-4 col-sm-4 col-form-label"></label>
						<div class="col-md-8 col-sm-8">
							<button type="submit" class="btn btn-primary">Guardar</button>
						</div>
					</div>
				</form>
			</div>
		</div>

		{% endblock %}
</body>

</html>

reportes/templates/reportes_auto.html
{% extends './base.html' %}
{% load static %}
<head>
    {% block head %}
    	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="{% static './assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static './assets/plugins/DataTables/extensions/Buttons/css/buttons.bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static './assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css' %}" rel="stylesheet" />
	<!-- ================== END PAGE LEVEL STYLE ================== -->
    {% endblock %}
</head>
<body >
	{% block content %}
		<!-- begin page-header -->
		<h1 class="page-header">GAP<small> </small></h1>
		<!-- end page-header -->
			
		<!-- begin panel -->
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<h4 class="panel-title">Recomendaciones</h4>
			</div>
			<br>
			<div class="btn-group pull-right">
				<form method="get" action="/reportes/grafico_recomendaciones/">
                {% csrf_token%}
    				<button type="submit" class="btn btn-primary">Gráfico de Recomendaciones</button>
				</form>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<form method="get" action="/reportes/grafico_gantt/">
                {% csrf_token%}
    				<button type="submit" class="btn btn-primary">Gantt de Recomendaciones</button>
				</form>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
            <div class="panel-body">
			<!-- begin row -->
				<div class="row">
				    <!-- begin col-10 -->
				    <div class="col-lg-12">
				        <!-- begin panel -->
	                    <div class="panel panel-inverse">
	                        <!-- begin panel-body -->
	                        <div class="panel-body">
	                            <table id="data-table-buttons" class="table table-striped table-bordered">
	                                <thead>
	                                    <tr>
	                                    	<th class="text-nowrap">Recomendación</th>
	                                    	<th class="text-nowrap">Cargo recomendado a resolver</th>
	                                        <th class="text-nowrap">Vigencia</th>
	                                        <th class="text-nowrap">Ley/Decreto afectado</th>
	                                        <th class="text-nowrap">Establecer Encargado</th>
	                                    </tr>
	                                </thead>
	                                <tbody>
	                                	{% for recomau in recomau %}
	                                    <tr class="odd gradeX">
	                                    	<td>{{ recomau.recomendacion.recomendacion }}</td>
	                                    	<td>{{ recomau.recomendacion.cargo_recomendado}}</td>
	                                        <td>{{ recomau.vigencia|date:"d M , Y"}}</td>
	                                        <td>{% for aspectoslegales in aspectoslegales %}
	                                        		{% if recomau.recomendacion.pregunta.control.seccion.dominio == aspectoslegales.dominio %}
	                                        			{{ aspectoslegales.aspecto_legal.tipo_norma}}<br>
	                                        		{% endif %}
	                                        {% endfor %}

	                                    	</td>
	                                        <td><form method="get" action="/reportes/reportes_auto/establecer_encargado/">
                    					{% csrf_token%}
                    						<input id="id_recomendacion" name="id_recomendacion" hidden value="{{ recomau.recomendacion.id_rec }}">
                    						{% if recomau.cumplimiento.usuario_delegado == NULL%}
                        						<button type="submit" class="btn btn-primary">Elegir</button>
                        					{% elif recomau.cumplimiento.cumplimiento == True %}
                        						<b> Recomendación Cumplida</b>
                        					{% elif recomau.cumplimiento.usuario_delegado != NULL%}
                        						<b> En Ejecución</b>
                        					{% endif%}
                    							</form></td>
	                                        
	                                    {% endfor %}
	                                    </tr>
	                                </tbody>
	                            </table>
	                        </div>
	                        <!-- end panel-body -->
	                    </div>
	                    <!-- end panel -->
	                </div>
	                <!-- end col-10 -->
	            </div>
            <!-- end row -->
			</div>
		</div>
	{% endblock %}
	{% block scripts %}

	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static './assets/plugins/DataTables/media/js/jquery.dataTables.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/dataTables.buttons.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.bootstrap.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.flash.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/jszip.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/pdfmake.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/vfs_fonts.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.html5.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.print.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static './assets/js/demo/table-manage-buttons.demo.min.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->

	<script>
		$(document).ready(function() {
			App.init();
			TableManageButtons.init();
		});
	</script>
	{% endblock %}
</body>
</html>

reportes/templates/ver_leyes_dominio.html
{% extends './base.html' %}
{% load static %}
<head>
    {% block head %}
    	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="{% static './assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static './assets/plugins/DataTables/extensions/Buttons/css/buttons.bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static './assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css' %}" rel="stylesheet" />
	<!-- ================== END PAGE LEVEL STYLE ================== -->
    {% endblock %}

</head>
<body >
	{% block content %}
		<!-- begin page-header -->
		<h1 class="page-header">Aspectos Legales<small> </small></h1>
		<!-- end page-header -->
			
		<!-- begin panel -->
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<h4 class="panel-title">Leyes y Decretos</h4>
			</div>
			<br>
			<div class="btn-group pull-right">
                <form method="get" action="agregar_leyes_dominio/">
                {% csrf_token%}
                    <input id="id_dominio" name="id_dominio" hidden value="{{ id_dominio }}">
    				<button type="submit" class="btn btn-primary">Agregar</button>
				</form>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
			<div class="panel-body">
			
			<!-- begin row -->
			<div class="row">
			    <!-- begin col-10 -->
			    <div class="col-lg-12">
			        <!-- begin panel -->
                    <div class="panel panel-inverse">
                        <!-- begin panel-body -->
                        <div class="panel-body">
                            <table id="data-table-buttons" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                    	<!-- <th class="text-nowrap">Descripción</th> -->
                                    	<th class="text-nowrap">Tipo de Norma</th>
                                    	<th class="text-nowrap">Fecha de Publicación</th>
                                    	<!-- <th class="text-nowrap">Fecha de Promulgación</th> -->
                                        <th class="text-nowrap">Organismo</th>
                                        <!-- <th class="text-nowrap">Título</th> -->
                                        <!-- <th class="text-nowrap">Tipo de Version</th> -->
                                        <th class="text-nowrap">Inicio de Vigencia</th>
                                        <th class="text-nowrap">Id de Norma</th>
                                        <!-- <th class="text-nowrap">Texto Derogado</th> -->
                                        <th class="text-nowrap">Última Modificacion</th>
                                        <!-- <th class="text-nowrap">URL</th> -->
                                        <th class="text-nowrap">Eliminar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                	{% for dominio in dominio %}
                                    <tr class="odd gradeX">
                                    	<!-- <td>{{ aspecto_legal.descripcion }}</td> -->
                                    	<td>{{ dominio.aspecto_legal.tipo_norma }}</td>
                                    	<td>{{ dominio.aspecto_legal.fecha_publicacion|date:"M d, Y" }}</td>
                                    	<!-- <td>{{ aspecto_legal.fecha_promulgacion|date:"M d, Y" }}</td> -->
                                        <td>{{ dominio.aspecto_legal.organismo }}</td>
                                        <!-- <td>{{ aspecto_legal.titulo }}</td> -->
                                        <!-- <td>{{ aspecto_legal.tipo_version }}</td> -->
                                        <td>{{ dominio.aspecto_legal.inicio_vigencia|date:"M d, Y" }}</td>
                                        <td>{{ dominio.aspecto_legal.id_norma }}</td>
                                        <!-- <td>{{ aspecto_legal.texto_derogado }}</td> -->
                                        <td>{{ dominio.aspecto_legal.ultima_modificacion|date:"M d, Y" }}</td>
                                        <!-- <td>{{ aspecto_legal.url }}</td> -->
                                        <td><form method="get" action="eliminar_leyes_dominio/">
                                            {% csrf_token%}
                                                <input id="id_aspectoslegales" name="id_aspectoslegales" hidden value="{{ dominio.aspecto_legal.id_asl }}">
                                                <input id="id_dominio" name="id_dominio" hidden value="{{ dominio.dominio.id_d }}">
                                                <button type="submit" class="btn btn-danger">Eliminar</button>
                                            </form></td>
                                    {% endfor %}
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- end panel-body -->
                    </div>
                    <!-- end panel -->
                </div>
                <!-- end col-10 -->
            </div>
            <!-- end row -->
			</div>
		</div>
	{% endblock %}

	{% block scripts %}

	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static './assets/plugins/DataTables/media/js/jquery.dataTables.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/dataTables.buttons.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.bootstrap.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.flash.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/jszip.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/pdfmake.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/vfs_fonts.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.html5.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Buttons/js/buttons.print.min.js' %}"></script>
	<script src="{% static './assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static './assets/js/demo/table-manage-buttons.demo.min.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->

	<script>
		$(document).ready(function() {
			App.init();
			TableManageButtons.init();
		});
	</script>
	{% endblock %}
</body>

</html>